# Generated by Django 5.0.7 on 2024-07-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name', models.CharField(max_length=50, unique=True)),
                ('star_constellation', models.TextField(blank=True, max_length=50, null=True)),
                ('star_type', models.TextField(blank=True, max_length=50, null=True)),
                ('star_distance', models.TextField(blank=True, max_length=25, null=True)),
                ('star_mass', models.TextField(blank=True, max_length=25, null=True)),
                ('star_temperature', models.TextField(blank=True, max_length=25, null=True)),
                ('star_period', models.TextField(blank=True, max_length=25, null=True)),
                ('star_turn_speed', models.TextField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
