# Generated by Django 4.2.5 on 2023-09-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='star_distance',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stars',
            name='star_mass',
            field=models.FloatField(max_length=25),
        ),
    ]
