# Generated by Django 4.2.5 on 2023-09-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name', models.TextField(max_length=50)),
                ('star_constellation', models.CharField(max_length=50)),
                ('star_type', models.CharField(max_length=50)),
                ('star_distance', models.FloatField(max_length=25)),
                ('star_mass', models.FloatField(max_length=25)),
                ('star_temperature', models.TextField(max_length=25)),
                ('star_period', models.TextField(max_length=25)),
                ('star_turn_speed', models.TextField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Stars',
        ),
    ]
