# Generated by Django 4.2.5 on 2024-07-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0003_alter_star_star_distance_alter_star_star_mass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='star_constellation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='star_distance',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='star_mass',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='star_period',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='star_temperature',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='star_turn_speed',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='star_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
