# Generated by Django 4.2.5 on 2024-07-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0004_alter_star_star_constellation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='star_constellation',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='star_type',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
