# Generated by Django 4.2.5 on 2024-07-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0005_alter_star_star_constellation_alter_star_star_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='star_name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
