# Generated by Django 4.2.5 on 2024-07-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0006_alter_star_star_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='star_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
